"""empty message

Revision ID: 0022af622ac2
Revises: 1e3bdf5a5501
Create Date: 2018-08-06 11:02:01.425454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0022af622ac2'
down_revision = '1e3bdf5a5501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('tags', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'tags')
    # ### end Alembic commands ###
