"""empty message

Revision ID: 4073e761590d
Revises: 71f7ad2ae176
Create Date: 2018-09-14 20:53:28.330522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4073e761590d'
down_revision = '71f7ad2ae176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
